travis:
  secure:
    BINSTAR_TOKEN: J1N/6oAH5FNDY4zouFqK818stT4i6bdrVjP5U3Jy82Egq8k7riptGfvp8HxoP1sx+iW3xdnAmhqvmtdzsm2IHQYwFiZml/chBTrlpGW2azdS2An9f/kneHFPCXpZv7dxnRyfoXo2q/cAJFBo5g107e4XR6JFQQr0p7w6rAntbtkJKQ8rGsan1nuP8kYpn92u/zfM0ZEbgN7SP1CG+OPfZ6pjWwLMMq4l0f82OH3hcRNVca/BMZJKp+Wq+xPJIC2nbiWvQq11dzH9i+DcdVE909h4rPY8f5TANlsa3IWOy80j5Pa4hBvp/P6oNrv+AhgFcSHDTJG8wc8JS3PgLVeOsZ1V4MLvpEprI5M6wNhFLzCQZ54mUkxuHTDdI5rVMQUoYs1WHID4LzikpDDXN2sVkc3apQjhhVAW+FpFNtBDjctyFrRNffT5QTazIxr5uVKw/4mNkvz7FRnGENMNPvFYU4cMTp8I8CRgbNLAHVpcvF/AVmd79g2lkqVi0H70O5/gl79R5vLATmjjfMLlHrFCmzJkkWvc3mkk4FoNRXBK01ESsP7I5Wf13HCLC9PIxOMi70b0wPJDViEhq0KzugMAj2+8Q+fPvC3xwgI7QfY5OW4hxuqnTyxcgluFC9Ht0Z4yrATBQi6Q5eAVwiKuYXRkp3xsH9Ay+dJ/a9xq9qfD3ac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
